name: rag

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - faiss-cpu
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.1
  - transformers=4.44.2
  - sentence-transformers=3.0.1